-- AlterTable
ALTER TABLE "public"."REGISTRO_CLINICOS" ADD COLUMN     "id_Tipo" SMALLINT NOT NULL DEFAULT 1,
ADD COLUMN     "tipoProntuarioId_Tipo" SMALLINT;

-- CreateTable
CREATE TABLE "public"."TIPO_PRONTUARIO" (
    "ID_Tipo" SMALLSERIAL NOT NULL,
    "nome" VARCHAR NOT NULL,

    CONSTRAINT "TIPO_PRONTUARIO_pkey" PRIMARY KEY ("ID_Tipo")
);

-- AddForeignKey
ALTER TABLE "public"."REGISTRO_CLINICOS" ADD CONSTRAINT "REGISTRO_CLINICOS_tipoProntuarioId_Tipo_fkey" FOREIGN KEY ("tipoProntuarioId_Tipo") REFERENCES "public"."TIPO_PRONTUARIO"("ID_Tipo") ON DELETE SET NULL ON UPDATE CASCADE;
