services:
  backend:
    container_name: arca_backend
    image: pedrokourly/arca-backend:latest

    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_AUDIENCE: arca_users
      JWT_TOKEN_ISSUER: arca_api
      JWT_TTL: ${JWT_TTL}
    
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:3333/health').then(r => {if(!r.ok) throw new Error(); process.exit(0)}).catch(e => process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 5

      start_period: 30s

    networks:
      - arca-net

  frontend:
    container_name: arca_frontend
    image: pedrokourly/arca-frontend:latest

    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

    depends_on:
      backend:
        condition: service_healthy
    networks:
      - arca-net

networks:
  arca-net:
    driver: bridge