services:
  backend:
    container_name: arca_backend
    image: pedrokourly/arca-backend:latest

    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_AUDIENCE: arca_users
      JWT_TOKEN_ISSUER: arca_api
      JWT_TTL: ${JWT_TTL}

    networks:
      - arca-net

  frontend:
    container_name: arca_frontend
    image: pedrokourly/arca-frontend:latest

    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

    networks:
      - arca-net

networks:
  arca-net:
    driver: bridge