services:
  backend:
    container_name: arca_backend
    image: pedrokourly/arca-backend:latest
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_AUDIENCE: arca_users
      JWT_TOKEN_ISSUER: arca_api
      JWT_TTL: ${JWT_TTL}
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - arca-net

  frontend:
    container_name: arca_frontend
    image: pedrokourly/arca-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

    depends_on:
      backend:
        condition: service_healthy
    networks:
      - arca-net

networks:
  arca-net:
    driver: bridge