/*
  Warnings:

  - Added the required column `id_Tipo_Atendimento` to the `ATENDIMENTOS` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "public"."ATENDIMENTOS" ADD COLUMN     "id_Tipo_Atendimento" SMALLINT NOT NULL;

-- CreateTable
CREATE TABLE "public"."TIPO_ATENDIMENTO" (
    "ID_Tipo_Atendimento" SMALLSERIAL NOT NULL,
    "nome" VARCHAR NOT NULL,

    CONSTRAINT "TIPO_ATENDIMENTO_pkey" PRIMARY KEY ("ID_Tipo_Atendimento")
);

-- AddForeignKey
ALTER TABLE "public"."USUARIOS" ADD CONSTRAINT "USUARIOS_ID_Role_fkey" FOREIGN KEY ("ID_Role") REFERENCES "public"."ROLES"("ID_Role") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."REGISTRO_CLINICOS" ADD CONSTRAINT "REGISTRO_CLINICOS_id_Lista_fkey" FOREIGN KEY ("id_Lista") REFERENCES "public"."LISTA_ESPERA"("ID_Lista") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."REGISTRO_CLINICOS" ADD CONSTRAINT "REGISTRO_CLINICOS_id_Atendimento_fkey" FOREIGN KEY ("id_Atendimento") REFERENCES "public"."ATENDIMENTOS"("ID_Atendimento") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."REGISTRO_CLINICOS" ADD CONSTRAINT "REGISTRO_CLINICOS_id_Status_fkey" FOREIGN KEY ("id_Status") REFERENCES "public"."STATUS_PRONTUARIO"("ID_Status") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."LOGS_AUDITORIA" ADD CONSTRAINT "LOGS_AUDITORIA_id_Usuario_Executor_fkey" FOREIGN KEY ("id_Usuario_Executor") REFERENCES "public"."USUARIOS"("ID_User") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_id_Lista_fkey" FOREIGN KEY ("id_Lista") REFERENCES "public"."LISTA_ESPERA"("ID_Lista") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_id_Estagiario_Executor_fkey" FOREIGN KEY ("id_Estagiario_Executor") REFERENCES "public"."USUARIOS"("ID_User") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_id_Supervisor_Executor_fkey" FOREIGN KEY ("id_Supervisor_Executor") REFERENCES "public"."USUARIOS"("ID_User") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_id_Status_fkey" FOREIGN KEY ("id_Status") REFERENCES "public"."STATUS_ATENDIMENTO"("ID_Status") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_id_Tipo_Atendimento_fkey" FOREIGN KEY ("id_Tipo_Atendimento") REFERENCES "public"."TIPO_ATENDIMENTO"("ID_Tipo_Atendimento") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."LISTA_ESPERA" ADD CONSTRAINT "LISTA_ESPERA_id_Genero_fkey" FOREIGN KEY ("id_Genero") REFERENCES "public"."GENERO"("ID_Genero") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."LISTA_ESPERA" ADD CONSTRAINT "LISTA_ESPERA_id_Etnia_fkey" FOREIGN KEY ("id_Etnia") REFERENCES "public"."ETNIA"("ID_Etnia") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."LISTA_ESPERA" ADD CONSTRAINT "LISTA_ESPERA_id_Escolaridade_fkey" FOREIGN KEY ("id_Escolaridade") REFERENCES "public"."ESCOLARIDADES"("ID_Escolaridade") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."LISTA_ESPERA" ADD CONSTRAINT "LISTA_ESPERA_id_Status_fkey" FOREIGN KEY ("id_Status") REFERENCES "public"."STATUS_LISTA_ESPERA"("ID_Status") ON DELETE RESTRICT ON UPDATE CASCADE;
